UPDATE PERNYATAAN SET tipe= "B" WHERE ID_PERNYATAAN="9";
UPDATE PERNYATAAN SET tipe= "X" WHERE ID_PERNYATAAN="10";
UPDATE PERNYATAAN SET tipe= "O" WHERE ID_PERNYATAAN="36";
UPDATE PERNYATAAN SET tipe= "X" WHERE ID_PERNYATAAN="47";
UPDATE PERNYATAAN SET tipe= "F" WHERE ID_PERNYATAAN="57";
UPDATE PERNYATAAN SET tipe= "C" WHERE ID_PERNYATAAN="88";
UPDATE PERNYATAAN SET tipe= "K" WHERE ID_PERNYATAAN="95";
UPDATE PERNYATAAN SET tipe= "D" WHERE ID_PERNYATAAN="108";
UPDATE PERNYATAAN SET tipe= "A" WHERE ID_PERNYATAAN="116";
UPDATE PERNYATAAN SET tipe= "W" WHERE ID_PERNYATAAN="179";

